# Generated by Django 5.1.6 on 2025-02-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_profile_options_remove_profile_is_normal_user_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
